/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rtdposinventorysystem;

import Classes.DBQueries;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class dlgAddStock extends javax.swing.JDialog {

    /**
     * Creates new form dlgAddStock
     */
    public dlgAddStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        stockID.setText(StockCount());
    }
    
    String StockCount(){
        String str = "";
        DBQueries dbStock = new DBQueries();
        try{
            dbStock.ConnectToDatabase();
            dbStock.StockID();
            if(dbStock.rs.next()){
               str=""+(dbStock.rs.getInt(1)+1);
            }
            dbStock.rs.close();
            dbStock.st.close();
            dbStock.con.close();
           
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        return str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        productID = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        prodDescription = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        unit = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        prod_id = new javax.swing.JTextField();
        txtcombocategory = new javax.swing.JTextField();
        txtbrand = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        supplier = new javax.swing.JLabel();
        DatePurchase = new javax.swing.JLabel();
        invoice = new javax.swing.JLabel();
        expiration = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtsupplier = new javax.swing.JTextField();
        datepurchase = new com.toedter.calendar.JDateChooser();
        invoicenumber = new javax.swing.JTextField();
        expirationdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        stockID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        costprice = new javax.swing.JLabel();
        retailprice = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtcurrentprice = new javax.swing.JTextField();
        txtretailprice = new javax.swing.JTextField();
        qty1 = new javax.swing.JTextField();
        damage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 240, 240));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD NEW STOCK");
        jPanel3.add(jLabel2);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jButton1.setText("CANCEL");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 128, 42));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save 1.png"))); // NOI18N
        jButton2.setText("SAVE");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 130, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel5.setLayout(new java.awt.GridLayout(6, 0));

        productID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productID.setText("Product ID:");
        jPanel5.add(productID);

        category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category.setText("Category Name:");
        jPanel5.add(category);

        brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brand.setText("Brand Name:");
        jPanel5.add(brand);

        prodDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prodDescription.setText("Product Description:");
        jPanel5.add(prodDescription);

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.setText("Color:");
        jPanel5.add(color);

        unit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unit.setText("Unit:");
        jPanel5.add(unit);

        jPanel6.setLayout(new java.awt.GridLayout(6, 0));

        prod_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prod_idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prod_idKeyReleased(evt);
            }
        });
        jPanel6.add(prod_id);

        txtcombocategory.setEditable(false);
        txtcombocategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcombocategoryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcombocategoryKeyReleased(evt);
            }
        });
        jPanel6.add(txtcombocategory);

        txtbrand.setEditable(false);
        txtbrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbrandKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbrandKeyReleased(evt);
            }
        });
        jPanel6.add(txtbrand);

        txtdescription.setEditable(false);
        jPanel6.add(txtdescription);

        txtcolor.setEditable(false);
        jPanel6.add(txtcolor);

        txtUnit.setEditable(false);
        jPanel6.add(txtUnit);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("(Scan /Enter Barcode)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 250));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel8.setLayout(new java.awt.GridLayout(4, 0));

        supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supplier.setText("Supplier Name:");
        jPanel8.add(supplier);

        DatePurchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DatePurchase.setText("Date Purchased:");
        jPanel8.add(DatePurchase);

        invoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoice.setText("Invoice Number:");
        jPanel8.add(invoice);

        expiration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expiration.setText("Expiration Date:");
        jPanel8.add(expiration);

        jPanel9.setLayout(new java.awt.GridLayout(4, 0));

        txtsupplier.setEditable(false);
        txtsupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupplierKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierKeyReleased(evt);
            }
        });
        jPanel9.add(txtsupplier);
        jPanel9.add(datepurchase);
        jPanel9.add(invoicenumber);
        jPanel9.add(expirationdate);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 390, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("(Scan /Enter Barcode)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        stockID.setBackground(new java.awt.Color(255, 255, 255));
        stockID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stockID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockID.setText("Stock ID:");
        stockID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(stockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Stock ID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amount Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel11.setLayout(new java.awt.GridLayout(4, 0));

        costprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costprice.setText("Current Price:");
        jPanel11.add(costprice);

        retailprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        retailprice.setText("Current Retail Price:");
        jPanel11.add(retailprice);

        qty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qty.setText("Qty:");
        jPanel11.add(qty);

        subtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotal.setText("Damaged:");
        jPanel11.add(subtotal);

        jPanel12.setLayout(new java.awt.GridLayout(4, 0));

        txtcurrentprice.setEditable(false);
        txtcurrentprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcurrentprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcurrentprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcurrentpriceFocusLost(evt);
            }
        });
        jPanel12.add(txtcurrentprice);

        txtretailprice.setEditable(false);
        txtretailprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtretailprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtretailprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtretailpriceKeyReleased(evt);
            }
        });
        jPanel12.add(txtretailprice);

        qty1.setEditable(false);
        qty1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(qty1);

        damage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        damage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(damage);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 290, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcurrentpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcurrentpriceFocusLost

    }//GEN-LAST:event_txtcurrentpriceFocusLost

    private void txtretailpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtretailpriceKeyReleased
        // TODO add your handling code here:
//        String cost_price = cost_price1.getText();
//        String qty1= quantity.getText();
//
//        if (!cost_price.equals("") && !cost_price.equals("0")) {
//            double costprice1 = Double.parseDouble(cost_price);
//            double mp = costprice1 / 100 * markup;
//            double Vat = (((costprice1 / 1.12)) / 100) * vat;
//            System.out.println(costprice1 + " " + markup + " " + vat);
//            double totalRetailPrice = (costprice1 + markup + vat);
//            retail.setText("" + formatter.format(totalRetailPrice));
//            int qty = Integer.parseInt(qty1);
//            double sub = costprice1 * qty;
//            txtsubtotal.setText(""+formatter.format(sub));
//
//        } else {
//            retail.setText("0");
//        }
    }//GEN-LAST:event_txtretailpriceKeyReleased

    private void prod_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_idKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_prod_idKeyPressed

    private void prod_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_idKeyReleased
        // TODO add your handling code here:
        int pcode = evt.getKeyCode();
        String prodcode = prod_id.getText();
        
        if(pcode==10){
            if(prodcode.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Please Scan/Enter Barcode Number!", "ERROR", JOptionPane.ERROR_MESSAGE);
                prod_id.requestFocus();
                return;
            }
            
            DBQueries dbStock = new DBQueries();
            try{
                dbStock.ConnectToDatabase();
                dbStock.searchProductForStocks(prodcode);
                if(dbStock.rs.next()){
                    txtcombocategory.setText(dbStock.rs.getString("category_name"));
                    txtbrand.setText(dbStock.rs.getString("brand_name"));
                    txtdescription.setText(dbStock.rs.getString("prod_description"));
                    txtcolor.setText(dbStock.rs.getString("color_name"));
                    txtUnit.setText(dbStock.rs.getString("unit_name"));
                    txtsupplier.setText(dbStock.rs.getString("sup_name"));
                    txtcurrentprice.setText(dbStock.rs.getString("cost_price"));
                    txtretailprice.setText(dbStock.rs.getString("retail_price"));
                    
                }else{
                    Toolkit.getDefaultToolkit().beep();
                    txtcombocategory.setText("COUDN'T FOUND");
                    txtbrand.setText("COUDN'T FOUND");
                    txtdescription.setText("COUDN'T FOUND");
                    txtcolor.setText("COUDN'T FOUND");
                    txtUnit.setText("COUDN'T FOUND");
                    txtsupplier.setText("COUDN'T FOUND");
                    txtcurrentprice.setText("COUDN'T FOUND");
                    txtretailprice.setText("COUDN'T FOUND");

                    txtcombocategory.setForeground(Color.RED);
                    txtbrand.setForeground(Color.RED);
                    txtdescription.setForeground(Color.RED);
                    txtcolor.setForeground(Color.RED);
                    txtUnit.setForeground(Color.RED);
                    txtsupplier.setForeground(Color.RED);
                    txtcurrentprice.setForeground(Color.RED);
                    txtretailprice.setForeground(Color.RED);
                }
            }catch(Exception e){
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            
            }finally {
                if (dbStock.con != null) {
                    dbStock.closeConnection();
                }

            }
        }
    }//GEN-LAST:event_prod_idKeyReleased
    
    private void txtcombocategoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcombocategoryKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcombocategoryKeyPressed

    private void txtcombocategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcombocategoryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcombocategoryKeyReleased

    private void txtbrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbrandKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrandKeyPressed

    private void txtbrandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbrandKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrandKeyReleased

    private void txtsupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierKeyPressed

    private void txtsupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgAddStock dialog = new dlgAddStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatePurchase;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel category;
    private javax.swing.JLabel color;
    private javax.swing.JLabel costprice;
    private javax.swing.JTextField damage;
    private com.toedter.calendar.JDateChooser datepurchase;
    private javax.swing.JLabel expiration;
    private com.toedter.calendar.JDateChooser expirationdate;
    private javax.swing.JLabel invoice;
    private javax.swing.JTextField invoicenumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel prodDescription;
    private javax.swing.JTextField prod_id;
    private javax.swing.JLabel productID;
    private javax.swing.JLabel qty;
    private javax.swing.JTextField qty1;
    private javax.swing.JLabel retailprice;
    private javax.swing.JLabel stockID;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel supplier;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtcombocategory;
    private javax.swing.JTextField txtcurrentprice;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtretailprice;
    private javax.swing.JTextField txtsupplier;
    private javax.swing.JLabel unit;
    // End of variables declaration//GEN-END:variables
}
