/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rtdposinventorysystem;

import Classes.DBQueries;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class dlgNewSupplier extends javax.swing.JDialog {
frmMain updatesupplier;
    /**
     * Creates new form dlgNewSupplier
     */
    public dlgNewSupplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DisplaySupplierNameToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        saveSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplier_table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        suppliercode = new javax.swing.JLabel();
        suppliername = new javax.swing.JLabel();
        supplierAddress = new javax.swing.JLabel();
        supplierEMAIL = new javax.swing.JLabel();
        suppliercontact = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        supplier_code = new javax.swing.JTextField();
        supplier_name = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jButton1.setText("CANCEL");

        saveSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save 1.png"))); // NOI18N
        saveSupplier.setText("SAVE");
        saveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSupplierActionPerformed(evt);
            }
        });

        supplier_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        supplier_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Supplier Code", "Supplier Name", "Address", "Email Address", "Contact No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplier_table.setAutoscrolls(false);
        jScrollPane1.setViewportView(supplier_table);
        if (supplier_table.getColumnModel().getColumnCount() > 0) {
            supplier_table.getColumnModel().getColumn(0).setMinWidth(35);
            supplier_table.getColumnModel().getColumn(0).setPreferredWidth(35);
            supplier_table.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(5, 0));

        suppliercode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suppliercode.setText("Supplier Code:");
        jPanel5.add(suppliercode);

        suppliername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suppliername.setText("Supplier Name:");
        jPanel5.add(suppliername);

        supplierAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierAddress.setText("Addresss:");
        jPanel5.add(supplierAddress);

        supplierEMAIL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierEMAIL.setText("Email Address:");
        jPanel5.add(supplierEMAIL);

        suppliercontact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suppliercontact.setText("Contact No. :");
        jPanel5.add(suppliercontact);

        jPanel6.setLayout(new java.awt.GridLayout(5, 0));
        jPanel6.add(supplier_code);

        supplier_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.add(supplier_name);

        address1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.add(address1);

        email1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.add(email1);

        contact1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.add(contact1);

        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        edit.setText("UPDATE");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW CATEGORY");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void DisplaySupplierNameToTable() {
        DBQueries database14 = new DBQueries();
        try {
            database14.ConnectToDatabase();
            database14.viewSupplierName();
            DefaultTableModel model = (DefaultTableModel) supplier_table.getModel();
            model.setRowCount(0);
            int i = 1;
            while (database14.rs.next()) {
                model.addRow(new Object[]{
                    i,
                    database14.rs.getString("sup_id"),
                    database14.rs.getString("sup_name"),
                    database14.rs.getString("sup_address"),
                    database14.rs.getString("sup_email"),
                    database14.rs.getString("sup_contact")

                });
            }
            i++;
        } catch (Exception e) {

        }

    }
    private void saveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSupplierActionPerformed
        // TODO add your handling code here
        String suppliercode = supplier_code.getText();
        String suppliername = supplier_name.getText();
        String address = address1.getText();
        String email = email1.getText();
        String contact = contact1.getText();
        DBQueries database13 = new DBQueries();
        try {
            database13.ConnectToDatabase();
            int i = JOptionPane.showConfirmDialog(null, "Are you sure?", "CONFIRMATION", 2);
            if (i == 0) {
                database13.insertNewSupplierName(suppliercode, suppliername, address, email, contact);
                JOptionPane.showMessageDialog(null, "New Supplier Name ADDED !!");
                //                refresh();
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        dispose();

    }//GEN-LAST:event_saveSupplierActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
          dlgUpdateSupplier update = new dlgUpdateSupplier(updatesupplier, true);

        int i = supplier_table.getSelectedRow();
        try {
            update.setData(supplier_table.getValueAt(i, 1).toString(),
                           supplier_table.getValueAt(i, 2).toString(),
                           supplier_table.getValueAt(i, 3).toString(),
                           supplier_table.getValueAt(i, 4).toString(),
                           supplier_table.getValueAt(i, 5).toString());
            update.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Select a row");
        }
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgNewSupplier dialog = new dlgNewSupplier(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JTextField contact1;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveSupplier;
    private javax.swing.JLabel supplierAddress;
    private javax.swing.JLabel supplierEMAIL;
    private javax.swing.JTextField supplier_code;
    private javax.swing.JTextField supplier_name;
    private javax.swing.JTable supplier_table;
    private javax.swing.JLabel suppliercode;
    private javax.swing.JLabel suppliercontact;
    private javax.swing.JLabel suppliername;
    // End of variables declaration//GEN-END:variables
}
