/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rtdposinventorysystem;

import Classes.DBQueries;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class dlgUpdateProduct extends javax.swing.JDialog {

    /**
     * Creates new form dlgUpdateProduct
     */
    public dlgUpdateProduct(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();

       getCategoryName();
       getBrandName();
       getNewColor();
       getUnitName();
    }

    public void setData(String prodCode, String category, String brand, String description, String color, String unit, double cost_price, double retail_price,
            double discount, int warnLevel) {
        this.prod_id.setText(prodCode);
        this.combocategory2.setSelectedItem(""+category);
        this.combobrand2.setSelectedItem(""+brand);
        this.prod_dess2.setText(description);
        this.combocolor2.setSelectedItem(""+color);
        this.combounit2.setSelectedItem(""+unit);
        this.cost_price1.setText("" + cost_price);
        this.retail.setText("" + retail_price);
        this.warn.setText("" + warnLevel);

        //this.Integer.parseInt(CUS_CONTACT.setText().toString());
    }

    void getCategoryName() {
        DBQueries database7 = new DBQueries();
        try {
            database7.ConnectToDatabase();
            database7.setCategoryName();
//            combocategory.removeAllItems();
            while (database7.rs.next()) {
                combocategory2.addItem(database7.rs.getString(1));

            }
            combocategory2.addItem("New CategoryName");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (database7.con != null) {
                database7.closeConnection();
            }
        }
    }
    
    void getUnitName() {
        DBQueries database22 = new DBQueries();
        try {
            database22.ConnectToDatabase();
            database22.setNewUnitName();
//            combounit.removeAllItems();
            while (database22.rs.next()) {
                combounit2.addItem(database22.rs.getString(1));

            }
            combounit2.addItem("New Unit Name");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (database22.con != null) {
                database22.closeConnection();
            }
        }
    }

    void getNewColor() {
        DBQueries database25 = new DBQueries();
        try {
            database25.ConnectToDatabase();
            database25.setNewColor();
//            combocolor.removeAllItems();
            while (database25.rs.next()) {
                combocolor2.addItem(database25.rs.getString(1));

            }
            combocolor2.addItem("New Color Name");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (database25.con != null) {
                database25.closeConnection();
            }
        }
    }

    void getBrandName() {
        DBQueries database16 = new DBQueries();
        try {
            database16.ConnectToDatabase();
            database16.setBrandName();
//            combobrand.removeAllItems();
            while (database16.rs.next()) {
                combobrand2.addItem(database16.rs.getString(1));

            }
            combobrand2.addItem("New Brand Name");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (database16.con != null) {
                database16.closeConnection();
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        productID2 = new javax.swing.JLabel();
        category2 = new javax.swing.JLabel();
        brand2 = new javax.swing.JLabel();
        prodDescription2 = new javax.swing.JLabel();
        color2 = new javax.swing.JLabel();
        unit2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        prod_id = new javax.swing.JTextField();
        combocategory2 = new javax.swing.JComboBox();
        combobrand2 = new javax.swing.JComboBox();
        prod_dess2 = new javax.swing.JTextField();
        combocolor2 = new javax.swing.JComboBox();
        combounit2 = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        costprice = new javax.swing.JLabel();
        retailprice = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        warnlevel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        cost_price1 = new javax.swing.JTextField();
        retail = new javax.swing.JTextField();
        discount1 = new javax.swing.JTextField();
        warn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        updateProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE PRODUCT");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel10.setLayout(new java.awt.GridLayout(6, 0));

        productID2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productID2.setText("Product ID:");
        jPanel10.add(productID2);

        category2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category2.setText("Category Name:");
        jPanel10.add(category2);

        brand2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brand2.setText("Brand Name:");
        jPanel10.add(brand2);

        prodDescription2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prodDescription2.setText("Product Description:");
        jPanel10.add(prodDescription2);

        color2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color2.setText("Color:");
        jPanel10.add(color2);

        unit2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unit2.setText("Unit:");
        jPanel10.add(unit2);

        jPanel11.setLayout(new java.awt.GridLayout(6, 0));
        jPanel11.add(prod_id);

        combocategory2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combocategory2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        combocategory2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combocategory2ItemStateChanged(evt);
            }
        });
        combocategory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocategory2ActionPerformed(evt);
            }
        });
        jPanel11.add(combocategory2);

        combobrand2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combobrand2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        combobrand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobrand2ActionPerformed(evt);
            }
        });
        jPanel11.add(combobrand2);
        jPanel11.add(prod_dess2);

        combocolor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combocolor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        combocolor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocolor2ActionPerformed(evt);
            }
        });
        jPanel11.add(combocolor2);

        combounit2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combounit2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        combounit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combounit2ActionPerformed(evt);
            }
        });
        jPanel11.add(combounit2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amount Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel13.setLayout(new java.awt.GridLayout(4, 0));

        costprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costprice.setText("Cost Price:");
        jPanel13.add(costprice);

        retailprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        retailprice.setText("Retail Price:");
        jPanel13.add(retailprice);

        discount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        discount.setText("Discount:");
        jPanel13.add(discount);

        warnlevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warnlevel.setText("Warn Level:");
        jPanel13.add(warnlevel);

        jPanel14.setLayout(new java.awt.GridLayout(4, 0));

        cost_price1.setBackground(new java.awt.Color(240, 240, 240));
        cost_price1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cost_price1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cost_price1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cost_price1KeyReleased(evt);
            }
        });
        jPanel14.add(cost_price1);

        retail.setBackground(new java.awt.Color(240, 240, 240));
        retail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        retail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(retail);

        discount1.setBackground(new java.awt.Color(240, 240, 240));
        discount1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        discount1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(discount1);

        warn.setBackground(new java.awt.Color(240, 240, 240));
        warn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        warn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnActionPerformed(evt);
            }
        });
        jPanel14.add(warn);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        updateProd.setText("UPDATE");
        updateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateProd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combocategory2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combocategory2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combocategory2ItemStateChanged

    private void combocategory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocategory2ActionPerformed
        // TODO add your handling code here:
//        if (combocategory.getSelectedItem().equals("New Category")) {
//            dlgNewcategory newcat = new dlgNewcategory(dlgcategory1, true);
//            newcat.setVisible(true);
//        }
    }//GEN-LAST:event_combocategory2ActionPerformed

    private void combobrand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobrand2ActionPerformed
        // TODO add your handling code here:
//        if(combobrand.getSelectedItem().equals("New Brand Name")){
//            dlgNewBrand newb = new dlgNewBrand(dlgbrand,true);
//            newb.setVisible(true);
//        }
    }//GEN-LAST:event_combobrand2ActionPerformed

    private void combocolor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocolor2ActionPerformed
        // TODO add your handling code here:
//        if(combocolor.getSelectedItem().equals("New Color Name")){
//            dlgNewColor newcolor = new dlgNewColor(dlgcolor,true);
//            newcolor.setVisible(true);
//        }
    }//GEN-LAST:event_combocolor2ActionPerformed

    private void combounit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combounit2ActionPerformed
        // TODO add your handling code here:
//        if(combounit.getSelectedItem().equals("New Unit Name")){
//            dlgNewUnit newunit = new dlgNewUnit(dlgunit,true);
//            newunit.setVisible(true);
//        }
    }//GEN-LAST:event_combounit2ActionPerformed

    private void cost_price1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cost_price1KeyReleased
        // TODO add your handling code here:
//        String cost_price = cost_price1.getText();
//        String qty1= quantity.getText();
//
//        if (!cost_price.equals("") && !cost_price.equals("0")) {
//            double costprice1 = Double.parseDouble(cost_price);
//            double mp = costprice1 / 100 * markup;
//            double Vat = (((costprice1 / 1.12)) / 100) * vat;
//            System.out.println(costprice1 + " " + markup + " " + vat);
//            double totalRetailPrice = (costprice1 + markup + vat);
//            retail.setText("" + formatter.format(totalRetailPrice));
//            int qty = Integer.parseInt(qty1);
//            double sub = costprice1 * qty;
//            txtsubtotal.setText(""+formatter.format(sub));
//
//        } else {
//            retail.setText("0");
//        }
    }//GEN-LAST:event_cost_price1KeyReleased

    public void comboDisplay() {
        DBQueries combo = new DBQueries();

    }

    private void updateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProdActionPerformed

        String prodCode = prod_id.getText();
        String category = combocategory2.getSelectedItem().toString();
        String brand = combobrand2.getSelectedItem().toString();
        String description = prod_dess2.getText();
        String unit1 = combounit2.getSelectedItem().toString();
        double costprice = Double.parseDouble(cost_price1.getText().toString());
        double retailprice = Double.parseDouble(retail.getText().toString());
        double discount = Double.parseDouble(discount1.getText().toString());
        int warning = Integer.parseInt(warn.getText().toString());

        DBQueries dbUpdate = new DBQueries();
        try {
            dbUpdate.ConnectToDatabase();
            int i = dbUpdate.UpdateProduct(prodCode, category, brand, description, unit1, costprice, retailprice, discount, warning);
            if (i > 0) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Updated Successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Update Failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
            dbUpdate.closeConnection();
        }


    }//GEN-LAST:event_updateProdActionPerformed


    private void warnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnActionPerformed
        // TODO add your handling code here:
//        String prodCode = prod_id.getText();

    }//GEN-LAST:event_warnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgUpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgUpdateProduct dialog = new dlgUpdateProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand2;
    private javax.swing.JLabel category2;
    private javax.swing.JLabel color2;
    public javax.swing.JComboBox combobrand2;
    private javax.swing.JComboBox combocategory2;
    public javax.swing.JComboBox combocolor2;
    public javax.swing.JComboBox combounit2;
    public javax.swing.JTextField cost_price1;
    private javax.swing.JLabel costprice;
    private javax.swing.JLabel discount;
    public javax.swing.JTextField discount1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel prodDescription2;
    public javax.swing.JTextField prod_dess2;
    public static javax.swing.JTextField prod_id;
    private javax.swing.JLabel productID2;
    public javax.swing.JTextField retail;
    private javax.swing.JLabel retailprice;
    private javax.swing.JLabel unit2;
    private javax.swing.JButton updateProd;
    public javax.swing.JTextField warn;
    private javax.swing.JLabel warnlevel;
    // End of variables declaration//GEN-END:variables
}
